### ISSUE TITLE
Add support for user accounts

### ISSUE THREAD

**Issue by lanesawyer** [lanesawyer/gshe#1]
We'd like users to be able to make an account so they can track which experiences they've had and how they stack up against other users (and the global stackrank in general).

**Comment by lanesawyer** [comment]
Users can now create accounts but I still need to make it so we store their information

**Comment by Stackranker** [comment]
Cool, that makes sense. Later on we might do fancy stuff like identify the 5 experiences of theirs that differ most in ranking from the Global.

**Comment by lanesawyer** [comment]
Finished. Basic user information is now being stored.

**Comment by Stackranker** [comment]
Great!
