### ISSUE TITLE
Submit 1000 experiences to Lane as the seed pool

### ISSUE THREAD

**Issue by Stackranker** [lanesawyer/gshe#13]
Wanted to give you an update- I expect to have a list of 1000 experiences for you within days. We can use the 1000 as our base set, and then work toward enabling users to add experiences. 

I plan to share it with you via Google Sheet- will that work?

**Comment by lanesawyer** [comment]
Yep, Google Sheets will work just fine! I'll be able to upload the data to Firebase pretty easily from that format.

**Comment by Stackranker** [comment]
Did I already share this with you? If not, it's (https://docs.google.com/spreadsheets/d/1okrEqfGd3jMf9uNJIcDwjhpAirOg4mJ5ikIUfy8gudc/edit?usp=sharing). Should I close this issue?
