### ISSUE TITLE
Create user profile page

### ISSUE THREAD

**Issue by lanesawyer** [lanesawyer/gshe#6]

**Comment by lanesawyer** [comment]
Profile page now has basic ability to change password and email

**Comment by Stackranker** [comment]
Cool.

Should we consider using already-built onboarding and user profile modules? Perhaps we've already crossed this bridge- but I bet there are some, including bundles that offer optional demographic questions. The already-built solutions may also anticipate future needs that we're not currently considering. 

Perhaps it's just as easy to build ourselves though- you're more of an expert on the pros/cons here.

**Comment by lanesawyer** [comment]
There aren't really any "plug-n-play" modules for user profiles. I've built out most of it though, and Firebase does a ton of the work for us. It'll be easy to expand and include any more demographic info that we want.
